"""add contact quote training tables

Revision ID: 312c79282e02
Revises: 77e088d69b5b
Create Date: 2026-01-07 15:51:19.719487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312c79282e02'
down_revision = '77e088d69b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_email'), ['email'], unique=False)

    op.create_table('quote_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_request_email'), ['email'], unique=False)

    op.create_table('training_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_registration_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_registration_email'))

    op.drop_table('training_registration')
    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_request_email'))

    op.drop_table('quote_request')
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_email'))

    op.drop_table('contact_message')
    # ### end Alembic commands ###
