"""tool add part_number and tier pricing

Revision ID: 3e290642b440
Revises: b54bed465607
Create Date: 2026-01-07 21:29:40.262567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e290642b440'
down_revision = 'b54bed465607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_number', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('daily_price_8_30', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tool_part_number'), ['part_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_part_number'))
        batch_op.drop_column('daily_price_8_30')
        batch_op.drop_column('part_number')

    # ### end Alembic commands ###
